version: '3.8'
services:
  service-1:
    image: seacloud_image
    ports:
      - "8081:80"
    volumes:
      - ./Service1_Main:/usr/share/nginx/html 

  service-2:
    image: seacloud_image
    ports:
      - "8082:80"
    volumes:
      - ./Service2_Auth:/usr/share/nginx/html

  service-3:
    image: seacloud_image
    ports:
      - "8083:80"
    volumes:
      - ./Service3_Developer:/usr/share/nginx/html

  service-4:
    image: seacloud_image
    ports:
      - "8084:80"
    volumes:
      - ./Service4_IT:/usr/share/nginx/html

  service-5:
    image: seacloud_image
    ports:
      - "8085:80"
    volumes:
      - ./Service5_Zoom:/usr/share/nginx/html 
